name: CI

on:
  - push

jobs:
  terraform-validate:
    name: Validate terraform configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform fmt -check -recursive
      - run: terraform validate
